### ISSUE TITLE
Add compatibility to OS X (Installation)

### ISSUE THREAD

**Issue by pantuza** [pantuza/Lonely-Arm#1]
The way source files includes GLU, GLUT libraries are different in OS X. Also, the package names in the Homebrew package manager. This issues has two tasks:
- [x] Add compatibility for #include inside source files;
- [x] Update README adding how to install software on OS X;

**Comment by Git-Jiro** [comment]
Hi, I will have a look at this!

**Comment by Git-Jiro** [comment]
Hi, I got it compiling for OS X! Have a look: https://github.com/Git-Jiro/homebrew-jiro/blob/master/lonely-arm.rb

To install this in OS X, you just have to run this command:
brew install --HEAD Git-Jiro/homebrew-jiro/lonely-arm

(This will not yet work in OS X 10.11 with Xcode 8 installed. Please wait until https://github.com/Homebrew/homebrew-x11/pull/261 is merged. Then it will work there as well.)

**Comment by pantuza** [comment]
Hey @Git-Jiro , thank you for your time working on it but this issue was already solved by [this pull request](https://github.com/pantuza/Lonely-Arm/pull/2).

**Comment by Git-Jiro** [comment]
Oh. Glad your problem is solved!
